### ISSUE TITLE
Build Failed while Creating dist Files

### ISSUE THREAD

**Issue by ZenithClown** [ZenithClown/VisualCrossing#1]
## Overview
[NOTE]: # ( Give a BRIEF summary of your problem )
Unable to build python package using `python -m build`

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install `build` if not already installed: **`python -m pip install --upgrade build`**
2. Run `build` commands as **`python -m build`**

### Error Traceback
```bash
PS E:\Visual Crossing\VisualCrossing> python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting dependencies for sdist...
C:\Users\debma\AppData\Local\Temp\build-env-kcmhic5p\lib\site-packages\setuptools\dist.py:487: UserWarning: Normalizing '0.0.1-beta' to '0.0.1b0'
  warnings.warn(tmpl.format(**locals()))
running egg_info
creating VisualCrossing.egg-info
writing VisualCrossing.egg-info\PKG-INFO
writing dependency_links to VisualCrossing.egg-info\dependency_links.txt
writing top-level names to VisualCrossing.egg-info\top_level.txt
writing manifest file 'VisualCrossing.egg-info\SOURCES.txt'
reading manifest file 'VisualCrossing.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 1: unknown action 'inlude'

warning: manifest_maker: MANIFEST.in, line 7: unknown action 'requirements.txt'

adding license file 'LICENSE'
writing manifest file 'VisualCrossing.egg-info\SOURCES.txt'
* Building sdist...
C:\Users\debma\AppData\Local\Temp\build-env-kcmhic5p\lib\site-packages\setuptools\dist.py:487: UserWarning: Normalizing '0.0.1-beta' to '0.0.1b0'
  warnings.warn(tmpl.format(**locals()))
running sdist
running egg_info
writing VisualCrossing.egg-info\PKG-INFO
writing dependency_links to VisualCrossing.egg-info\dependency_links.txt
writing top-level names to VisualCrossing.egg-info\top_level.txt
reading manifest file 'VisualCrossing.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 1: unknown action 'inlude'

warning: manifest_maker: MANIFEST.in, line 7: unknown action 'requirements.txt'

adding license file 'LICENSE'
writing manifest file 'VisualCrossing.egg-info\SOURCES.txt'
running check
creating VisualCrossing-0.0.1b0
creating VisualCrossing-0.0.1b0\VisualCrossing
creating VisualCrossing-0.0.1b0\VisualCrossing.egg-info
copying files to VisualCrossing-0.0.1b0...
copying CHANGELOG.md -> VisualCrossing-0.0.1b0
copying LICENSE -> VisualCrossing-0.0.1b0
copying MANIFEST.in -> VisualCrossing-0.0.1b0
copying README.md -> VisualCrossing-0.0.1b0
copying setup.cfg -> VisualCrossing-0.0.1b0
copying setup.py -> VisualCrossing-0.0.1b0
copying VisualCrossing\__init__.py -> VisualCrossing-0.0.1b0\VisualCrossing
copying VisualCrossing\api.py -> VisualCrossing-0.0.1b0\VisualCrossing
copying VisualCrossing\errors.py -> VisualCrossing-0.0.1b0\VisualCrossing
copying VisualCrossing.egg-info\PKG-INFO -> VisualCrossing-0.0.1b0\VisualCrossing.egg-info
copying VisualCrossing.egg-info\SOURCES.txt -> VisualCrossing-0.0.1b0\VisualCrossing.egg-info
copying VisualCrossing.egg-info\dependency_links.txt -> VisualCrossing-0.0.1b0\VisualCrossing.egg-info
copying VisualCrossing.egg-info\top_level.txt -> VisualCrossing-0.0.1b0\VisualCrossing.egg-info
Writing VisualCrossing-0.0.1b0\setup.cfg
Creating tar archive
removing 'VisualCrossing-0.0.1b0' (and everything under it)
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    VERSION = open(VERSIONFILE, "rt").read() # always read as str()
FileNotFoundError: [Errno 2] No such file or directory: 'static\\VERSION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 349, in <module>
    main()
  File "D:\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "D:\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 117, in get_requires_for_build_wheel
    return hook(config_settings)
  File "C:\Users\debma\AppData\Local\Temp\build-env-b5i0_cm7\lib\site-packages\setuptools\build_meta.py", line 154, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "C:\Users\debma\AppData\Local\Temp\build-env-b5i0_cm7\lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "C:\Users\debma\AppData\Local\Temp\build-env-b5i0_cm7\lib\site-packages\setuptools\build_meta.py", line 258, in run_setup
    super(_BuildMetaLegacyBackend,
  File "C:\Users\debma\AppData\Local\Temp\build-env-b5i0_cm7\lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 22, in <module>
    raise RuntimeError("unable to run setuptools")
RuntimeError: unable to run setuptools

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```

## Context
[NOTE]: # ( Give us any additional information you may have. )
[NOTE]: # ( Also, Paste error detailed traceback )

- [x] Fix `MANIFEST.in` : keyword `include` is missing at Line-12
- [x] Understand why `static/VERSION` is not understood

[NOTE]: # ( Pick choices based on your environment )
Python Version : 3.8.3
Operating System : Microsoft Windows 10 Home Single Language (10.0.19043 N/A Build 19043)

**Comment by ZenithClown** [comment]
Fixed `MANIFEST.in` and `FileNotFoundError` on 7f060b41f8b25bbc6a7c4ae8bab88c7db846bf3a..c8facd0304245c394301fef747878bb74149fb0b, but **build** failed as:

```shell
PS E:\Visual Crossing\VisualCrossing> python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting dependencies for sdist...
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 349, in <module>
    main()
  File "D:\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "D:\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 284, in get_requires_for_build_sdist
    return hook(config_settings)
  File "C:\Users\debma\AppData\Local\Temp\build-env-3e62nveb\lib\site-packages\setuptools\build_meta.py", line 159, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "C:\Users\debma\AppData\Local\Temp\build-env-3e62nveb\lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "C:\Users\debma\AppData\Local\Temp\build-env-3e62nveb\lib\site-packages\setuptools\build_meta.py", line 258, in run_setup
    super(_BuildMetaLegacyBackend,
  File "C:\Users\debma\AppData\Local\Temp\build-env-3e62nveb\lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 17, in <module>
    from VisualCrossing import (
  File "E:\Visual Crossing\VisualCrossing\VisualCrossing\__init__.py", line 20, in <module>
    from .api import API
  File "E:\Visual Crossing\VisualCrossing\VisualCrossing\api.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist
```

Check:
- [ ] is `requests` installed?
- [ ] is correct environment selected?
- [ ] does code works with direct-imports?

**Comment by ZenithClown** [comment]
Using `twine` instead to publish your PyPI package as follows:

```console
dPramanik@mint~:$ pip install twine
dPramanik@mint~:$ python setup.py sdist bdist_wheel # creates file in dist
dPramanik@mint~:$ twine check dist/* # check your package
```

Once you are satisfied with **build** and **test** you can now upload the package to PyPI. For this, first you can also test-upload, or directly publish with **`twine upload dist/*`**. More information is [available here](https://realpython.com/pypi-publish-python-package/).

**Note:** Do check package version number, as **`lib\site-packages\setuptools\dist.py:458: UserWarning: Normalizing '0.0.1-beta' to '0.0.1b0'`**, thus might create problem for documentation and  versioning (also check pypa/setuptools#308).
